language: cpp

sudo: true

compiler:
- g++

os:
- linux

before_install:
- make

script: ./main

branches:
  only:
  - master

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9