language: cpp

sudo: required

compiler:
- g++

os:
- linux

before_install:
- env CXX=g++-4.9 make

script: env LD_LIBRARY_PATH=$(pwd)/build/lib ./main

branches:
  only:
  - master

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9