/**
 * key word list
 */
KEYWORD("and",AND,RESERVED_KEYWORD)
KEYWORD("as",AS,RESERVED_KEYWORD)
KEYWORD("from",FROM,RESERVED_KEYWORD)
KEYWORD("or",OR,RESERVED_KEYWORD)
KEYWORD("select",SELECT,RESERVED_KEYWORD)
KEYWORD("where",WHERE,RESERVED_KEYWORD)


