/**
* key word list
*/
KEYWORD("and",AND,RESERVED_KEYWORD)
KEYWORD("as",AS,RESERVED_KEYWORD)
KEYWORD("from",FROM,RESERVED_KEYWORD)
KEYWORD("int",INT,COL_NAME_KEYWORD)
KEYWORD("left",LEFT,TYPE_FUNC_NAME_KEYWORD)
KEYWORD("like",LIKE,TYPE_FUNC_NAME_KEYWORD)
KEYWORD("or",OR,RESERVED_KEYWORD)
KEYWORD("right",RIGHT,TYPE_FUNC_NAME_KEYWORD)
KEYWORD("select",SELECT,RESERVED_KEYWORD)
KEYWORD("set",SET,UNRESERVED_KEYWORD)
KEYWORD("where",WHERE,RESERVED_KEYWORD)
